// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameApp.Context;

namespace VideoGameApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoGameApp.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("int")
                        .HasColumnName("Rating")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("Rating1");

                    b.HasKey("Id");

                    b.ToTable("Video_Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 5,
                            Genre = "Real-time",
                            Name = "Starcraft BroodWar",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 3,
                            Genre = "Real-time",
                            Name = "Starcraft 2",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = 2,
                            Genre = "MOBA",
                            Name = "League Of Legends",
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = 5,
                            Genre = "MOBA",
                            Name = "Dota",
                            Rating = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
